### ISSUE TITLE
Info display hangs with VDR 2.4.0 (and 2.2.0 partially)

### ISSUE THREAD

**Issue by DerPit** [vdr-projects/vdr-plugin-extrecmenu#1]
If I have extrecmenue enabled/loaded and select 'info' for one of my recordings, the display is basically dead:  If I use skindesigner/shady_KISS as theme, I cannot change to other tabs (record info / plot etc.), not even scroll a (long) plot text down.  Only 'back' works.
Using a lighter skin (skinnopacity) doing the same, I can see that the page is redrawn at high rate (1-2 per second).
I had seen this behavior before already with VDR 2.2.0, but with that one only while I was cutting some recording.  Now, with 2.4.0, it happens always

**Comment by M-Reimer** [comment]
This plugin is maintained here:
https://gitlab.com/kamel5/extrecmenung
If you still can reproduce this issue with his updated version, please create an Issue there.
